version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: personal-finance-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: personal-finance-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: iustin@notiustin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    restart: always

volumes:
  postgres-data:
  pgadmin-data: